theme: jekyll-theme-cayman
google_analytics: G-GDZZ8MJPVH
title: Kolossi
description: "Kolossi's blog"
show_downloads: false
plugins:
  - jemoji
exclude:
- Gemfile
- Gemfile.lock
- .gitignore
- .vscode
collections:
  articles:
    output: true
  quicktips:
    output: true
  bookmarks:
    output: true
defaults:
  - scope:
      path: ""
      type: "quicktips"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "bookmarks"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"