theme: jekyll-theme-cayman
google_analytics: G-GDZZ8MJPVH
title: Kolossi
description: "Kolossi's blog"
show_downloads: false
collections:
  articles:
    output: true
  quicktips:
    output: true
defaults:
  - scope:
      path: ""
      type: "quicktips"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"